### ISSUE TITLE
(plugin workbox-inject) TypeError: Cannot read property 'sections' of null

### ISSUE THREAD

**Issue by runette** [chromeos/static-site-scaffold-modules#10]
I have a workbox template file for injectManifest - it was working with v4 and has now been changed so it should work with v5. But all i get is

TypeError: Cannot read property 'sections' of null.

```
import {skipWaiting, clientsClaim} from 'workbox-core';
import {precacheAndRoute} from 'workbox-precaching';
import {registerRoute} from 'workbox-routing';
import {StaleWhileRevalidate, CacheFirst, NetworkFirst} from 'workbox-strategies';
import {CacheableResponsePlugin} from 'workbox-cacheable-response';
import {ExpirationPlugin} from 'workbox-expiration';


skipWaiting();
clientsClaim();

/**
 * The workboxSW.precacheAndRoute() method efficiently caches and responds to
 * requests for URLs in the manifest.
 * See https://goo.gl/S9QRab
 */


precacheAndRoute(self.__WB_MANIFEST);

// Cache the Google Fonts stylesheets with a stale-while-revalidate strategy.
registerRoute(
  /^https:\/\/fonts\.googleapis\.com/,
  new StaleWhileRevalidate({
    cacheName: 'google-fonts-stylesheets',
  })
);

// Cache the underlying font files with a cache-first strategy for 1 year.
registerRoute(
  /^https:\/\/fonts\.gstatic\.com/,
  new CacheFirst({
    cacheName: 'google-fonts-webfonts',
    plugins: [
      new CacheableResponsePlugin({
        statuses: [0, 200],
      }),
      new ExpirationPlugin({
        maxAgeSeconds: 60 * 60 * 24 * 365,
        maxEntries: 31,
      }),
    ],
  })
);

registerRoute(
  '/database',
  new NetworkFirst({
    cacheName: 'static-resources',
  })
);

registerRoute(
  '/',
  new StaleWhileRevalidate({
    cacheName: 'static-resources',
  })
);

registerRoute(
  /http.*\.(?:js|css|mjs)$/,
  new CacheFirst({
    cacheName: 'libraries',
    plugins: [
      new ExpirationPlugin({
        maxAgeSeconds: 30 * 24 * 60 * 60, // 30 Days
      }),
    ],
  }),
);

registerRoute(
  /\.(?:png|gif|jpg|jpeg|svg)$/,
  new CacheFirst({
    cacheName: 'images',
    plugins: [
      new ExpirationPlugin({
        maxEntries: 60,
        maxAgeSeconds: 30 * 24 * 60 * 60, // 30 Days
      }),
    ],
  }),
);
```

**Comment by jeffposnick** [comment]
That generally looks as expected from the Workbox point of view, yes.

Any chance you could either point us to a live deployment or a GitHub repo that we could check out to reproduce locally, @runette?

**Comment by jeffposnick** [comment]
Also, do you get that error at build time, when running Rollup, or at runtime when accessing your web app and loading the SW?

**Comment by runette** [comment]
It happens at build time.

You can see the code at https://github.com/runette/ultima-ratio and the live site at www.bigcannonproject.org - but I went back to orchestrating Rollup and Workbox manually since I could not get the plug in working.

**Comment by jeffposnick** [comment]
Given that you've reverted https://github.com/runette/ultima-ratio, I can't reproduce anything there. Is there a specific `git` commit that I could try out that would demonstrate the problem?

Also, @Snugug, this sounds more like an error specific to your plugin than something tied to Workbox if it only occurs at build time.

**Comment by Snugug** [comment]
Hey @runette, sorry for the delay here. I'm going to release a new version of the plugin later today with updates @jeffposnick has made, can you check tomorrow and tell me if it's still a problem? Thanks!

**Comment by runette** [comment]
Will try

**Comment by Snugug** [comment]
Sorry for the slight delay, I've just released the new version. It's a major bump, so please read the README and make sure your config is up to date
