### ISSUE TITLE
(eleventy-plugin-safe-external-links) Plugin seems to empty out the head tag

### ISSUE THREAD

**Issue by hirusi** [chromeos/static-site-scaffold-modules#23]
After enabling this plugin, the `<head>` tag in all my HTML files appears to be empty.

If it helps, the content passed by Eleventy is the content inside the body tag, without the body tag included in the input.

## Versions
@11ty/eleventy: v0.11.0
eleventy-plugin-safe-external-links: v0.1.4

**Comment by Snugug** [comment]
Can you please write a reduced sample where you're seeing this happen so I can debug further? Thanks!

**Comment by hirusi** [comment]
@Snugug Sure, I'll find some time this week and get you a sample public repo. :+1:
