### ISSUE TITLE
SVG images are not working

### ISSUE THREAD

**Issue by 1Iv4N** [chromeos/static-site-scaffold-modules#3]
The following markdown:
```## ![keyboard icon](/images/icons/keyboard.svg) A headline with an icon``` 

Will throw the following error:
```
Problem writing Eleventy templates: (more in DEBUG output)
> Having trouble writing template: public/en/style-guide/typography/index.html

`TemplateWriterWriteError` was thrown
> Cannot set property 'mime' of undefined
    at Template.respimg (.../node_modules/eleventy-plugin-local-respimg/lib/respimg.js:92:25)
```

**Comment by Snugug** [comment]
Hmm… ok. I'll look into this.

**Comment by Snugug** [comment]
I've written a [minimal test case](https://github.com/chromeos/static-site-scaffold-modules/blob/master/modules/eleventy-plugin-local-respimg/tests/svgs.js#L56-L72) from what the rendered markdown you've provided would be (this plugin works after markdown is rendered). The test case you've provided passes, not fails. Can you please provided a minimum test case that can reproduce the error you're seeing?

**Comment by Snugug** [comment]
Closing this as there's been no feedback on the provided testcase.

**Comment by leifniem** [comment]
Sorry for necrobumping, but i ran into this issue when working on my portfolio recently and while not minimal i can provide the repo if it is any help.

https://github.com/leifniem/website-netlify/tree/2d272f44c1b7cfad6f91980149c89bbda91624f8

**Comment by stevenwoodson** [comment]
Apologies for commenting on a closed issue, but wanted to share that I too had this error message relating to an SVG. After a bit of trial and error finding the SVG that was causing the trouble I realized the SVG code did not include the usual meta information at the top. It started as this when I was getting an error
```
<svg viewBox="0 0 629 200" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
```
and the error was cleared after changing that to 

```
<?xml version="1.0" standalone="no"?>
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
<svg viewBox="0 0 629 200" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
```

Hoping this helps someone else searching for a resolution to this same `'mime' of undefined` issue for SVG images.
