### ISSUE TITLE
[eleventy-plugin-local-respimg] Feature request: Allow overriding loading="lazy"

### ISSUE THREAD

**Issue by stevygee** [chromeos/static-site-scaffold-modules#31]
Version: 0.3.1

Using `lazy: true` in the config adds loading="lazy" to all img tags. I would like to use this, but also be able to explicitly set loading="eager" on some images, which are displayed above the fold. However, loading="eager" always gets overwritten if it is set.
Individual overrides per image is already possible when specifying the "sizes" attribute.

**Comment by Snugug** [comment]
Yup I'm happy to support this, and it seems pretty straight forward. If you'd like to submit a PR feel free to do so, otherwise when I get some cycles I'll work on it.
