### ISSUE TITLE
process.env.NODE_ENV replacement in Workbox plugin?

### ISSUE THREAD

**Issue by jeffposnick** [chromeos/static-site-scaffold-modules#4]
Workbox uses `process.env.NODE_ENV` throughout its unbundled source code to conditionally include debug logging/assertions. When bundling the source with `webpack`, this [gets replaced automatically](https://webpack.js.org/configuration/mode/). When using Rollup, developers have to manually add in the `replace` Rollup plugin into their config, or else the resulting bundled code isn't valid JavaScript.

Perhaps your plugin can automatically handle that replacement?

CC: @philipwalton

C.f. https://github.com/GoogleChrome/web.dev/pull/2246#issuecomment-592268564

**Comment by Snugug** [comment]
I'm a little torn on this as I'm not sure if we want to be making a global change like this in a smaller plugin, but I'm willing to consider doing it or, if possible, confining it to just Workbox.

**Comment by jeffposnick** [comment]
Yes, I think confining to Workbox was what I had in mind.

**Comment by Snugug** [comment]
@jeffposnick given our previous conversation, is this still relevant?

**Comment by jeffposnick** [comment]
I'm cool with closing it in favor of including the `@rollup/plugin-replace` configuration in the documentation.
